{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "helm-charts-delivery-pipeline.serviceAccountName" . }}
  labels:
{{ include "helm-charts-delivery-pipeline.labels" . | indent 4 }}
{{- end -}}
